# -*- coding: utf-8 -*-
"""Tema2_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wbh5CsAdNwBQRX-uw-GZjucnZahRepzq
"""

# ================================================
# Life Expectancy - Regularizare Polinomiala
# Cod Final cu DOAR 2 grafice
# ================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score

# ==============================================================
# 1. Incarcare dataset
# ==============================================================
data = pd.read_csv("Life Expectancy Data.csv")

# Curatare nume coloane
data.columns = (
    data.columns
        .str.strip()
        .str.replace(' +', ' ', regex=True)
        .str.replace(' ', '_')
        .str.replace('-', '_')
        .str.replace('/', '_')
        .str.replace('__', '_')
)

# Selectie coloane relevante
cols = [
    'Status', 'Life_expectancy', 'Adult_Mortality', 'infant_deaths',
    'Alcohol', 'Hepatitis_B', 'BMI', 'under_five_deaths', 'Total_expenditure',
    'Diphtheria', 'HIV_AIDS', 'GDP', 'thinness_1_19_years',
    'Income_composition_of_resources', 'Schooling'
]

data = data[cols]

# Tratare valori lipsa
data['Life_expectancy'] = data['Life_expectancy'].fillna(data['Life_expectancy'].median())

num_cols = data.columns.drop(['Status', 'Life_expectancy'])
for col in num_cols:
    data[col] = data[col].fillna(data[col].median())

data['Status'] = data['Status'].map({'Developing':0, 'Developed':1})

# ==============================================================
# 2. Definire X si y + Split + Scalare
# ==============================================================
X = data.drop('Life_expectancy', axis=1)
y = data['Life_expectancy']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

# ==============================================================
# 3. Functie evaluare model
# ==============================================================
def train_and_evaluate(model, X_train_poly, X_test_poly, y_train, y_test):
    model.fit(X_train_poly, y_train)
    y_pred = model.predict(X_test_poly)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return y_pred, mse, r2, model

# ==============================================================
# 4. Modelare cu polinom grad 3
# ==============================================================
deg = 3
poly = PolynomialFeatures(degree=deg, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Linear
pred_lin, mse_lin, r2_lin, lr_model = train_and_evaluate(
    LinearRegression(), X_train_poly, X_test_poly, y_train, y_test
)

# Ridge
pred_ridge, mse_ridge, r2_ridge, ridge_model = train_and_evaluate(
    Ridge(alpha=1.0), X_train_poly, X_test_poly, y_train, y_test
)

# Lasso
pred_lasso, mse_lasso, r2_lasso, lasso_model = train_and_evaluate(
    Lasso(alpha=0.01, max_iter=20000), X_train_poly, X_test_poly, y_train, y_test
)

# ==============================================================
# 5. GRAFICUL 1 — MSE + R2 (două subploturi într-o singură figură)
# ==============================================================
plt.figure(figsize=(10,6))

plt.subplot(1,2,1)
plt.bar(["Linear","Ridge","Lasso"], [mse_lin, mse_ridge, mse_lasso],
        color=["red","blue","green"])
plt.title("Comparatie MSE (Grad 3)")
plt.ylabel("MSE")
plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.subplot(1,2,2)
plt.bar(["Linear","Ridge","Lasso"], [r2_lin, r2_ridge, r2_lasso],
        color=["red","blue","green"])
plt.title("Comparatie R² (Grad 3)")
plt.ylabel("R²")
plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

# ==============================================================
# 6. GRAFICUL 2 — Predictii vs Valori Reale
# ==============================================================
plt.figure(figsize=(12,6))
plt.plot(y_test.values, label="Valori reale", color="black", linewidth=2)
plt.plot(pred_lin, label="Linear", alpha=0.7)
plt.plot(pred_ridge, label="Ridge", alpha=0.7)
plt.plot(pred_lasso, label="Lasso", alpha=0.7)

plt.title("Predictii vs Valori Reale (Grad 3)")
plt.xlabel("Sample index")
plt.ylabel("Life Expectancy")
plt.legend()
plt.grid(True)
plt.show()

