# -*- coding: utf-8 -*-
"""Tema3_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BU7tQOeVgE1MRjw8D8YfFnJxXuh2zGM
"""

# IMPORTURI

import pandas as pd
import time
import matplotlib.pyplot as plt

from mlxtend.frequent_patterns import fpgrowth, apriori, association_rules



# 1. INCARCARE DATE
cons = pd.read_csv("consumption_user.csv")


# 2. SELECTARE COLOANE RELEVANTE
df = cons[['SUBJECT', 'SURVEY_DAY', 'FOODEX2_INGR_CODE', 'FOOD_AMOUNT_CONS']]

# eliminam inregistrarile fara consum efectiv
df = df[df['FOOD_AMOUNT_CONS'] > 0].copy()

# 3. VARIABILA BINARA (CONSUMAT / NU)
df['Consumed'] = True   # boolean pentru performanta mai buna


# 4. CONSTRUIREA TRANZACTIILOR (INDIVID + ZI)
basket = (
    df.groupby(['SUBJECT', 'SURVEY_DAY', 'FOODEX2_INGR_CODE'])['Consumed']
      .max()
      .unstack(fill_value=False)
)

print("Dimensiunea matricei tranzacționale:", basket.shape)



# 5. COMPARAȚIE FP-GROWTH vs APRIORI (PERFORMANTA)
supports = [0.02, 0.04, 0.06, 0.08]

fp_times = []
ap_times = []

fp_counts = []
ap_counts = []

for s in supports:
    # FP-Growth
    start = time.time()
    fp_itemsets = fpgrowth(basket, min_support=s)
    fp_times.append(time.time() - start)
    fp_counts.append(len(fp_itemsets))

    # Apriori
    start = time.time()
    ap_itemsets = apriori(basket, min_support=s)
    ap_times.append(time.time() - start)
    ap_counts.append(len(ap_itemsets))



# GRAFICUL 1: TIMP DE EXECUTIE

plt.figure()
plt.plot(supports, fp_times, marker='o', label='FP-Growth')
plt.plot(supports, ap_times, marker='o', label='Apriori')
plt.xlabel("Pragul minim de support")
plt.ylabel("Timp de execuție (secunde)")
plt.title("Compararea timpului de execuție: FP-Growth vs Apriori")
plt.legend()
plt.show()



# GRAFICUL 2: NUMAR ITEMSET-URI

plt.figure()
plt.plot(supports, fp_counts, marker='o', label='FP-Growth')
plt.plot(supports, ap_counts, marker='o', label='Apriori')
plt.xlabel("Pragul minim de support")
plt.ylabel("Număr de itemset-uri frecvente")
plt.title("Numărul de itemset-uri generate: FP-Growth vs Apriori")
plt.legend()
plt.show()


# 6. FP-GROWTH + REGULI DE ASOCIERE

frequent_itemsets = fpgrowth(
    basket,
    min_support=0.05,
    use_colnames=True,
    max_len=3
)

rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.6
)

# filtrare reguli relevante
rules = rules[rules['lift'] > 1.2]


# GRAFICUL 3: SUPPORT vs LIFT

plt.figure()
plt.scatter(rules['support'], rules['lift'])
plt.xlabel("Support")
plt.ylabel("Lift")
plt.title("Relația dintre support și lift pentru regulile FP-Growth")
plt.show()


# AFISARE REGULI

print(
    rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
    .sort_values('lift', ascending=False)
    .head(10)
)